import { MigrationInterface, QueryRunner } from "typeorm";

export class InitalSchema1771964988420 implements MigrationInterface {
    name = 'InitalSchema1771964988420'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "usuarios" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "auth0_id" character varying NOT NULL, "email" character varying NOT NULL, "nombre" character varying, "activo" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_1023a6b2d5f26f88002090da651" UNIQUE ("auth0_id"), CONSTRAINT "PK_d7281c63c176e152e4c531594a8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "empresas" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "ruc" character varying(11) NOT NULL, "razon_social" character varying NOT NULL, "nombre_comercial" character varying, "ubigeo" character varying, "direccion_fiscal" character varying, "sunat_env" character varying NOT NULL DEFAULT 'BETA', "sol_usuario" character varying, "sol_clave" character varying, "cert_pfx" bytea, "cert_password" character varying, "activo" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_febfecf7816478e76da58585a57" UNIQUE ("ruc"), CONSTRAINT "PK_ce7b122b37c6499bfd6520873e1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "roles" ("id" SMALLSERIAL NOT NULL, "nombre" text NOT NULL, "descripcion" text, CONSTRAINT "UQ_a5be7aa67e759e347b1c6464e10" UNIQUE ("nombre"), CONSTRAINT "PK_c1433d71a4838793a49dcad46ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sedes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "empresa_id" uuid NOT NULL, "nombre" character varying NOT NULL, "ubigeo" character varying, "direccion" character varying, "activo" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_c19965a2bcffe22a994ed8b426b" UNIQUE ("empresa_id", "nombre"), CONSTRAINT "PK_842a6b0ebcf810b57487748b822" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_sedes_empresa" ON "sedes" ("empresa_id") `);
        await queryRunner.query(`CREATE TABLE "usuarios_empresas_roles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "usuario_id" uuid NOT NULL, "empresa_id" uuid NOT NULL, "rol_id" smallint NOT NULL, "sede_id" uuid, "activo" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_7572d0e5ee90ebaf8c040be4752" UNIQUE ("usuario_id", "empresa_id", "rol_id", "sede_id"), CONSTRAINT "PK_1afd055065fd3d39d4952927b5d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_uer_lookup" ON "usuarios_empresas_roles" ("usuario_id", "empresa_id", "sede_id") `);
        await queryRunner.query(`CREATE TABLE "usuarios_empresas" ("usuario_id" uuid NOT NULL, "empresa_id" uuid NOT NULL, "activo" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_bdce039544a8477f1f1aaadf29b" PRIMARY KEY ("usuario_id", "empresa_id"))`);
        await queryRunner.query(`CREATE INDEX "idx_ue_empresa" ON "usuarios_empresas" ("empresa_id") `);
        await queryRunner.query(`CREATE TABLE "clientes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tipo_identificacion_id" smallint NOT NULL, "nro_doc" text NOT NULL, "razon_social_nombre" text NOT NULL, "direccion" text, "ubigeo" text, "email" text, "telefono" text, "activo" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "uq_clientes_tipo_doc" UNIQUE ("tipo_identificacion_id", "nro_doc"), CONSTRAINT "PK_d76bf3571d906e4e86470482c08" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_clientes_doc" ON "clientes" ("tipo_identificacion_id", "nro_doc") `);
        await queryRunner.query(`CREATE TABLE "tipos_identificacion" ("id" SMALLSERIAL NOT NULL, "codigo_sunat" character varying(2) NOT NULL, "nombre" text NOT NULL, "es_empresa" boolean NOT NULL DEFAULT false, "activo" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_a29d9c2498d8cd45d2f55571f4a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_daddebd3c1b37b21e9e2afbeec" ON "tipos_identificacion" ("codigo_sunat") `);
        await queryRunner.query(`CREATE TABLE "tipos_comprobante" ("id" SMALLSERIAL NOT NULL, "codigo_sunat" character varying(2) NOT NULL, "nombre" text NOT NULL, "requiere_cliente" boolean NOT NULL DEFAULT true, "permite_credito" boolean NOT NULL DEFAULT true, "activo" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_0d8c88f1a45150d7dabae509967" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_43c3e8e8aaa73942812fca3a8a" ON "tipos_comprobante" ("codigo_sunat") `);
        await queryRunner.query(`CREATE TABLE "series" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "empresa_id" uuid NOT NULL, "tipo_comprobante_id" smallint NOT NULL, "serie" text NOT NULL, "correlativo_actual" integer NOT NULL DEFAULT '0', "activo" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "uq_series_empresa_tipo_serie" UNIQUE ("empresa_id", "tipo_comprobante_id", "serie"), CONSTRAINT "PK_e725676647382eb54540d7128ba" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_series_empresa" ON "series" ("empresa_id") `);
        await queryRunner.query(`CREATE TYPE "public"."estado_comprobante" AS ENUM('DRAFT', 'EMITIDO', 'ACEPTADO', 'RECHAZADO', 'ANULADO')`);
        await queryRunner.query(`CREATE TABLE "comprobantes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "empresa_id" uuid NOT NULL, "sede_id" uuid NOT NULL, "serie_id" uuid NOT NULL, "cliente_id" uuid NOT NULL, "tipo_comprobante_id" smallint NOT NULL, "tipo_comprobante_codigo" character varying(2) NOT NULL, "serie" text NOT NULL, "correlativo" integer NOT NULL, "fecha_emision" TIMESTAMP WITH TIME ZONE NOT NULL, "moneda" character varying(3) NOT NULL, "tipo_cambio" numeric(12,4), "total_gravadas" numeric(14,2) NOT NULL DEFAULT '0', "total_inafectas" numeric(14,2) NOT NULL DEFAULT '0', "total_exoneradas" numeric(14,2) NOT NULL DEFAULT '0', "total_igv" numeric(14,2) NOT NULL DEFAULT '0', "total_isc" numeric(14,2) NOT NULL DEFAULT '0', "total_descuentos" numeric(14,2) NOT NULL DEFAULT '0', "total" numeric(14,2) NOT NULL, "estado" "public"."estado_comprobante" NOT NULL DEFAULT 'DRAFT', "observaciones" text, "created_by" uuid, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "uq_comp_legal_numero" UNIQUE ("empresa_id", "tipo_comprobante_codigo", "serie", "correlativo"), CONSTRAINT "PK_0c3ac75b725717ec0f082ece89b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_comp_cliente" ON "comprobantes" ("cliente_id") `);
        await queryRunner.query(`CREATE INDEX "idx_comp_empresa_fecha" ON "comprobantes" ("empresa_id", "fecha_emision") `);
        await queryRunner.query(`CREATE TYPE "public"."estado_sunat" AS ENUM('PENDIENTE', 'ENVIADO', 'ACEPTADO', 'RECHAZADO', 'OBSERVADO')`);
        await queryRunner.query(`CREATE TABLE "sunat_envios" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "empresa_id" uuid NOT NULL, "comprobante_id" uuid NOT NULL, "xml_path" text, "zip_path" text, "cdr_path" text, "ticket" text, "estado" "public"."estado_sunat" NOT NULL DEFAULT 'PENDIENTE', "codigo_error" text, "mensaje_error" text, "intentos" integer NOT NULL DEFAULT '0', "fecha_envio" TIMESTAMP WITH TIME ZONE, "fecha_respuesta" TIMESTAMP WITH TIME ZONE, CONSTRAINT "uq_sunat_comprobante" UNIQUE ("comprobante_id"), CONSTRAINT "REL_94467a282ab5ece0513b72a335" UNIQUE ("comprobante_id"), CONSTRAINT "PK_d5ee0bf37be33ab6f581db53748" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_sunat_empresa_estado" ON "sunat_envios" ("empresa_id", "estado") `);
        await queryRunner.query(`CREATE TABLE "productos_servicios" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "empresa_id" uuid NOT NULL, "codigo_interno" text, "descripcion" text NOT NULL, "unidad_medida" text NOT NULL, "precio_unitario" numeric(12,2) NOT NULL, "afectacion_igv" text NOT NULL, "es_servicio" boolean NOT NULL DEFAULT false, "activo" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "uq_prod_empresa_codigo" UNIQUE ("empresa_id", "codigo_interno"), CONSTRAINT "PK_1e53fea06036ab53240f69302ea" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_prod_empresa" ON "productos_servicios" ("empresa_id") `);
        await queryRunner.query(`CREATE TABLE "comprobante_referencias" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "empresa_id" uuid NOT NULL, "comprobante_id" uuid NOT NULL, "ref_comprobante_id" uuid NOT NULL, "tipo_relacion" character varying(2) NOT NULL, "motivo" text, CONSTRAINT "uq_ref_unica" UNIQUE ("comprobante_id", "ref_comprobante_id"), CONSTRAINT "PK_73210a84014c266926aacd0bc20" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_ref_comprobante_afectado" ON "comprobante_referencias" ("ref_comprobante_id") `);
        await queryRunner.query(`CREATE INDEX "idx_ref_comprobante" ON "comprobante_referencias" ("comprobante_id") `);
        await queryRunner.query(`CREATE INDEX "idx_ref_empresa" ON "comprobante_referencias" ("empresa_id") `);
        await queryRunner.query(`CREATE TABLE "comprobante_eventos" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "empresa_id" uuid NOT NULL, "comprobante_id" uuid NOT NULL, "tipo_evento" text NOT NULL, "detalle" text, "actor_usuario_id" uuid, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_c42ae461ab9e566b4d952200601" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_eventos_comprobante" ON "comprobante_eventos" ("comprobante_id") `);
        await queryRunner.query(`CREATE INDEX "idx_eventos_empresa" ON "comprobante_eventos" ("empresa_id") `);
        await queryRunner.query(`CREATE TABLE "comprobante_detalle" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "comprobante_id" uuid NOT NULL, "empresa_id" uuid NOT NULL, "item" integer NOT NULL, "producto_id" uuid, "descripcion" text NOT NULL, "unidad_medida" text NOT NULL, "cantidad" numeric(12,3) NOT NULL, "valor_unitario" numeric(12,6) NOT NULL, "precio_unitario" numeric(12,6) NOT NULL, "descuento" numeric(12,2) NOT NULL DEFAULT '0', "afectacion_igv" text NOT NULL, "igv_monto" numeric(14,2) NOT NULL DEFAULT '0', "isc_monto" numeric(14,2) DEFAULT '0', "total_linea" numeric(14,2) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "uq_detalle_comp_item" UNIQUE ("comprobante_id", "item"), CONSTRAINT "PK_e7eb773ee1cb31b6116aaaf403a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_detalle_empresa" ON "comprobante_detalle" ("empresa_id") `);
        await queryRunner.query(`ALTER TABLE "sedes" ADD CONSTRAINT "FK_0b51b2673f7d16c085ec17f157a" FOREIGN KEY ("empresa_id") REFERENCES "empresas"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "usuarios_empresas_roles" ADD CONSTRAINT "FK_2e84ecda577913794d5a3df7fb1" FOREIGN KEY ("usuario_id") REFERENCES "usuarios"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "usuarios_empresas_roles" ADD CONSTRAINT "FK_2e27710eb9a871e4674033ad61d" FOREIGN KEY ("empresa_id") REFERENCES "empresas"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "usuarios_empresas_roles" ADD CONSTRAINT "FK_231af753769ac1ad6057ab9c217" FOREIGN KEY ("rol_id") REFERENCES "roles"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "usuarios_empresas_roles" ADD CONSTRAINT "FK_0df27d25bfa96e614cebcc7bf3f" FOREIGN KEY ("sede_id") REFERENCES "sedes"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "usuarios_empresas" ADD CONSTRAINT "FK_4a51d238f7720fe8a0c73876430" FOREIGN KEY ("usuario_id") REFERENCES "usuarios"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "usuarios_empresas" ADD CONSTRAINT "FK_2438c9e2b8957cfccd917ce8afe" FOREIGN KEY ("empresa_id") REFERENCES "empresas"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "clientes" ADD CONSTRAINT "FK_b9b4ff6f2aca525127330c20ed1" FOREIGN KEY ("tipo_identificacion_id") REFERENCES "tipos_identificacion"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "series" ADD CONSTRAINT "FK_051fb87a537eb8017f11b51e79e" FOREIGN KEY ("empresa_id") REFERENCES "empresas"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "series" ADD CONSTRAINT "FK_4229753e1356b91b77b2db7e586" FOREIGN KEY ("tipo_comprobante_id") REFERENCES "tipos_comprobante"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comprobantes" ADD CONSTRAINT "FK_d157d356cd8fec4b9ddfca7efdf" FOREIGN KEY ("empresa_id") REFERENCES "empresas"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comprobantes" ADD CONSTRAINT "FK_e314e19736205b09833da3bd97f" FOREIGN KEY ("sede_id") REFERENCES "sedes"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comprobantes" ADD CONSTRAINT "FK_7fd43d90a32bc895caa9ebeaf86" FOREIGN KEY ("serie_id") REFERENCES "series"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comprobantes" ADD CONSTRAINT "FK_52efe547ddd86fa9592a8ab3dfe" FOREIGN KEY ("cliente_id") REFERENCES "clientes"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comprobantes" ADD CONSTRAINT "FK_671a964832c571429668273f70a" FOREIGN KEY ("tipo_comprobante_id") REFERENCES "tipos_comprobante"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comprobantes" ADD CONSTRAINT "FK_a1ed3c14bd64c27303f13a4d289" FOREIGN KEY ("created_by") REFERENCES "usuarios"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sunat_envios" ADD CONSTRAINT "FK_219203e948949626681b01279e4" FOREIGN KEY ("empresa_id") REFERENCES "empresas"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sunat_envios" ADD CONSTRAINT "FK_94467a282ab5ece0513b72a3353" FOREIGN KEY ("comprobante_id") REFERENCES "comprobantes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "productos_servicios" ADD CONSTRAINT "FK_390267f5d87b44648eb69ce6921" FOREIGN KEY ("empresa_id") REFERENCES "empresas"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comprobante_referencias" ADD CONSTRAINT "FK_0a1a4b60350c228cbbd83fb9c65" FOREIGN KEY ("empresa_id") REFERENCES "empresas"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comprobante_referencias" ADD CONSTRAINT "FK_751ec1f2852f844d4066fe7cf37" FOREIGN KEY ("comprobante_id") REFERENCES "comprobantes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comprobante_referencias" ADD CONSTRAINT "FK_53c74d84e2260159999734a5b14" FOREIGN KEY ("ref_comprobante_id") REFERENCES "comprobantes"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comprobante_eventos" ADD CONSTRAINT "FK_96b7c321ee6398c802fbb57f0e8" FOREIGN KEY ("empresa_id") REFERENCES "empresas"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comprobante_eventos" ADD CONSTRAINT "FK_806cca7b4aad68f30b6b61db921" FOREIGN KEY ("comprobante_id") REFERENCES "comprobantes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comprobante_eventos" ADD CONSTRAINT "FK_a0b1632ee5686486786cd77ed03" FOREIGN KEY ("actor_usuario_id") REFERENCES "usuarios"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comprobante_detalle" ADD CONSTRAINT "FK_8228c5d3975e800b4ade3a9a7e3" FOREIGN KEY ("comprobante_id") REFERENCES "comprobantes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comprobante_detalle" ADD CONSTRAINT "FK_c2f89c48870cf88f1a89f87a750" FOREIGN KEY ("empresa_id") REFERENCES "empresas"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comprobante_detalle" ADD CONSTRAINT "FK_ee81b39c40683389b52c3a80383" FOREIGN KEY ("producto_id") REFERENCES "productos_servicios"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "comprobante_detalle" DROP CONSTRAINT "FK_ee81b39c40683389b52c3a80383"`);
        await queryRunner.query(`ALTER TABLE "comprobante_detalle" DROP CONSTRAINT "FK_c2f89c48870cf88f1a89f87a750"`);
        await queryRunner.query(`ALTER TABLE "comprobante_detalle" DROP CONSTRAINT "FK_8228c5d3975e800b4ade3a9a7e3"`);
        await queryRunner.query(`ALTER TABLE "comprobante_eventos" DROP CONSTRAINT "FK_a0b1632ee5686486786cd77ed03"`);
        await queryRunner.query(`ALTER TABLE "comprobante_eventos" DROP CONSTRAINT "FK_806cca7b4aad68f30b6b61db921"`);
        await queryRunner.query(`ALTER TABLE "comprobante_eventos" DROP CONSTRAINT "FK_96b7c321ee6398c802fbb57f0e8"`);
        await queryRunner.query(`ALTER TABLE "comprobante_referencias" DROP CONSTRAINT "FK_53c74d84e2260159999734a5b14"`);
        await queryRunner.query(`ALTER TABLE "comprobante_referencias" DROP CONSTRAINT "FK_751ec1f2852f844d4066fe7cf37"`);
        await queryRunner.query(`ALTER TABLE "comprobante_referencias" DROP CONSTRAINT "FK_0a1a4b60350c228cbbd83fb9c65"`);
        await queryRunner.query(`ALTER TABLE "productos_servicios" DROP CONSTRAINT "FK_390267f5d87b44648eb69ce6921"`);
        await queryRunner.query(`ALTER TABLE "sunat_envios" DROP CONSTRAINT "FK_94467a282ab5ece0513b72a3353"`);
        await queryRunner.query(`ALTER TABLE "sunat_envios" DROP CONSTRAINT "FK_219203e948949626681b01279e4"`);
        await queryRunner.query(`ALTER TABLE "comprobantes" DROP CONSTRAINT "FK_a1ed3c14bd64c27303f13a4d289"`);
        await queryRunner.query(`ALTER TABLE "comprobantes" DROP CONSTRAINT "FK_671a964832c571429668273f70a"`);
        await queryRunner.query(`ALTER TABLE "comprobantes" DROP CONSTRAINT "FK_52efe547ddd86fa9592a8ab3dfe"`);
        await queryRunner.query(`ALTER TABLE "comprobantes" DROP CONSTRAINT "FK_7fd43d90a32bc895caa9ebeaf86"`);
        await queryRunner.query(`ALTER TABLE "comprobantes" DROP CONSTRAINT "FK_e314e19736205b09833da3bd97f"`);
        await queryRunner.query(`ALTER TABLE "comprobantes" DROP CONSTRAINT "FK_d157d356cd8fec4b9ddfca7efdf"`);
        await queryRunner.query(`ALTER TABLE "series" DROP CONSTRAINT "FK_4229753e1356b91b77b2db7e586"`);
        await queryRunner.query(`ALTER TABLE "series" DROP CONSTRAINT "FK_051fb87a537eb8017f11b51e79e"`);
        await queryRunner.query(`ALTER TABLE "clientes" DROP CONSTRAINT "FK_b9b4ff6f2aca525127330c20ed1"`);
        await queryRunner.query(`ALTER TABLE "usuarios_empresas" DROP CONSTRAINT "FK_2438c9e2b8957cfccd917ce8afe"`);
        await queryRunner.query(`ALTER TABLE "usuarios_empresas" DROP CONSTRAINT "FK_4a51d238f7720fe8a0c73876430"`);
        await queryRunner.query(`ALTER TABLE "usuarios_empresas_roles" DROP CONSTRAINT "FK_0df27d25bfa96e614cebcc7bf3f"`);
        await queryRunner.query(`ALTER TABLE "usuarios_empresas_roles" DROP CONSTRAINT "FK_231af753769ac1ad6057ab9c217"`);
        await queryRunner.query(`ALTER TABLE "usuarios_empresas_roles" DROP CONSTRAINT "FK_2e27710eb9a871e4674033ad61d"`);
        await queryRunner.query(`ALTER TABLE "usuarios_empresas_roles" DROP CONSTRAINT "FK_2e84ecda577913794d5a3df7fb1"`);
        await queryRunner.query(`ALTER TABLE "sedes" DROP CONSTRAINT "FK_0b51b2673f7d16c085ec17f157a"`);
        await queryRunner.query(`DROP INDEX "public"."idx_detalle_empresa"`);
        await queryRunner.query(`DROP TABLE "comprobante_detalle"`);
        await queryRunner.query(`DROP INDEX "public"."idx_eventos_empresa"`);
        await queryRunner.query(`DROP INDEX "public"."idx_eventos_comprobante"`);
        await queryRunner.query(`DROP TABLE "comprobante_eventos"`);
        await queryRunner.query(`DROP INDEX "public"."idx_ref_empresa"`);
        await queryRunner.query(`DROP INDEX "public"."idx_ref_comprobante"`);
        await queryRunner.query(`DROP INDEX "public"."idx_ref_comprobante_afectado"`);
        await queryRunner.query(`DROP TABLE "comprobante_referencias"`);
        await queryRunner.query(`DROP INDEX "public"."idx_prod_empresa"`);
        await queryRunner.query(`DROP TABLE "productos_servicios"`);
        await queryRunner.query(`DROP INDEX "public"."idx_sunat_empresa_estado"`);
        await queryRunner.query(`DROP TABLE "sunat_envios"`);
        await queryRunner.query(`DROP TYPE "public"."estado_sunat"`);
        await queryRunner.query(`DROP INDEX "public"."idx_comp_empresa_fecha"`);
        await queryRunner.query(`DROP INDEX "public"."idx_comp_cliente"`);
        await queryRunner.query(`DROP TABLE "comprobantes"`);
        await queryRunner.query(`DROP TYPE "public"."estado_comprobante"`);
        await queryRunner.query(`DROP INDEX "public"."idx_series_empresa"`);
        await queryRunner.query(`DROP TABLE "series"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_43c3e8e8aaa73942812fca3a8a"`);
        await queryRunner.query(`DROP TABLE "tipos_comprobante"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_daddebd3c1b37b21e9e2afbeec"`);
        await queryRunner.query(`DROP TABLE "tipos_identificacion"`);
        await queryRunner.query(`DROP INDEX "public"."idx_clientes_doc"`);
        await queryRunner.query(`DROP TABLE "clientes"`);
        await queryRunner.query(`DROP INDEX "public"."idx_ue_empresa"`);
        await queryRunner.query(`DROP TABLE "usuarios_empresas"`);
        await queryRunner.query(`DROP INDEX "public"."idx_uer_lookup"`);
        await queryRunner.query(`DROP TABLE "usuarios_empresas_roles"`);
        await queryRunner.query(`DROP INDEX "public"."idx_sedes_empresa"`);
        await queryRunner.query(`DROP TABLE "sedes"`);
        await queryRunner.query(`DROP TABLE "roles"`);
        await queryRunner.query(`DROP TABLE "empresas"`);
        await queryRunner.query(`DROP TABLE "usuarios"`);
    }

}
